-- NOTE: THIS IS AUTO GENERATED BY MATUGEN. CHANGES CAN AND WILL BE OVERWRITTEN
-- colors.lua

local color_scheme = {
	foreground = "#e9e0e7",
	background = "#161217",

	cursor_bg = "#e2b7f4",
	cursor_fg = "#432254",
	cursor_border = "#e2b7f4",

	selection_fg = "#432254",
	selection_bg = "#e2b7f4",

	scrollbar_thumb = "#4b444d",

	split = "#978e98",

	ansi = {
		"#181818",
		"#ffb4ab",
		"#e2b7f4",
		"#745086",
		"#e2b7f4",
		"#f5b7b7",
		"#d3c0d8",
		"#BAC2DE",
	},
	brights = {
		"#585B70",
		"#F38BA8",
		"#A6E3A1",
		"#F9E2AF",
		"#89B4FA",
		"#F5C2E7",
		"#94E2D5",
		"#A6ADC8",
	},

	indexed = { [136] = "#f5b7b7" },
	compose_cursor = "#d3c0d8",
	copy_mode_active_highlight_bg = { Color = "#161217" },
	copy_mode_active_highlight_fg = { AnsiColor = "Black" },
	copy_mode_inactive_highlight_bg = { Color = "#e2b7f4" },
	copy_mode_inactive_highlight_fg = { AnsiColor = "White" },

	quick_select_label_bg = { Color = "#d3c0d8" },
	quick_select_label_fg = { Color = "#382c3e" },
	quick_select_match_bg = { AnsiColor = "Navy" },
	quick_select_match_fg = { Color = "#e9e0e7" },

	input_selector_label_bg = { AnsiColor = "Black" },
	input_selector_label_fg = { Color = "#e9e0e7" },

	launcher_label_bg = { AnsiColor = "Black" },
	launcher_label_fg = { Color = "#e9e0e7" },

	tab_bar = {
		background = "#161217",

		active_tab = {
			bg_color = "#2d282e",
			fg_color = "#e9e0e7",
			intensity = "Normal",
			underline = "None",
			italic = false,
			strikethrough = false,
		},

		inactive_tab = {
			bg_color = "#221e24",
			fg_color = "#cec3ce",
		},

		inactive_tab_hover = {
			bg_color = "#383339",
			fg_color = "#e9e0e7",
			italic = true,
		},

		new_tab = {
			bg_color = "#221e24",
			fg_color = "#cec3ce",
		},

		new_tab_hover = {
			bg_color = "#383339",
			fg_color = "#e9e0e7",
			italic = true,
		},

		inactive_tab_edge = "#978e98",
	},
}

local window_frame = {
	active_titlebar_bg = "#161217",
	inactive_titlebar_bg = "#161217",
}

return { color_scheme = color_scheme, window_frame = window_frame }
