-- NOTE: THIS IS AUTO GENERATED BY MATUGEN. CHANGES CAN AND WILL BE OVERWRITTEN
-- colors.lua

local color_scheme = {
	foreground = "#e2e2e9",
	background = "#111318",

	cursor_bg = "#aec6ff",
	cursor_fg = "#112f60",
	cursor_border = "#aec6ff",

	selection_fg = "#112f60",
	selection_bg = "#aec6ff",

	scrollbar_thumb = "#44474f",

	split = "#8e9099",

	ansi = {
		"#181818",
		"#ffb4ab",
		"#aec6ff",
		"#445e91",
		"#aec6ff",
		"#debcdf",
		"#bfc6dc",
		"#BAC2DE",
	},
	brights = {
		"#585B70",
		"#F38BA8",
		"#A6E3A1",
		"#F9E2AF",
		"#89B4FA",
		"#F5C2E7",
		"#94E2D5",
		"#A6ADC8",
	},

	indexed = { [136] = "#debcdf" },
	compose_cursor = "#bfc6dc",
	copy_mode_active_highlight_bg = { Color = "#111318" },
	copy_mode_active_highlight_fg = { AnsiColor = "Black" },
	copy_mode_inactive_highlight_bg = { Color = "#aec6ff" },
	copy_mode_inactive_highlight_fg = { AnsiColor = "White" },

	quick_select_label_bg = { Color = "#bfc6dc" },
	quick_select_label_fg = { Color = "#293041" },
	quick_select_match_bg = { AnsiColor = "Navy" },
	quick_select_match_fg = { Color = "#e2e2e9" },

	input_selector_label_bg = { AnsiColor = "Black" },
	input_selector_label_fg = { Color = "#e2e2e9" },

	launcher_label_bg = { AnsiColor = "Black" },
	launcher_label_fg = { Color = "#e2e2e9" },

	tab_bar = {
		background = "#111318",

		active_tab = {
			bg_color = "#282a2f",
			fg_color = "#e2e2e9",
			intensity = "Normal",
			underline = "None",
			italic = false,
			strikethrough = false,
		},

		inactive_tab = {
			bg_color = "#1e1f25",
			fg_color = "#c5c6d0",
		},

		inactive_tab_hover = {
			bg_color = "#33353a",
			fg_color = "#e2e2e9",
			italic = true,
		},

		new_tab = {
			bg_color = "#1e1f25",
			fg_color = "#c5c6d0",
		},

		new_tab_hover = {
			bg_color = "#33353a",
			fg_color = "#e2e2e9",
			italic = true,
		},

		inactive_tab_edge = "#8e9099",
	},
}

local window_frame = {
	active_titlebar_bg = "#111318",
	inactive_titlebar_bg = "#111318",
}

return { color_scheme = color_scheme, window_frame = window_frame }
