-- NOTE: THIS IS AUTO GENERATED BY MATUGEN. CHANGES CAN AND WILL BE OVERWRITTEN
-- colors.lua

local color_scheme = {
	foreground = "#e1e2e9",
	background = "#111318",

	cursor_bg = "#a5c8fe",
	cursor_fg = "#00315d",
	cursor_border = "#a5c8fe",

	selection_fg = "#00315d",
	selection_bg = "#a5c8fe",

	scrollbar_thumb = "#43474e",

	split = "#8d9199",

	ansi = {
		"#181818",
		"#ffb4ab",
		"#a5c8fe",
		"#3b608f",
		"#a5c8fe",
		"#d9bde3",
		"#bcc7dc",
		"#BAC2DE",
	},
	brights = {
		"#585B70",
		"#F38BA8",
		"#A6E3A1",
		"#F9E2AF",
		"#89B4FA",
		"#F5C2E7",
		"#94E2D5",
		"#A6ADC8",
	},

	indexed = { [136] = "#d9bde3" },
	compose_cursor = "#bcc7dc",
	copy_mode_active_highlight_bg = { Color = "#111318" },
	copy_mode_active_highlight_fg = { AnsiColor = "Black" },
	copy_mode_inactive_highlight_bg = { Color = "#a5c8fe" },
	copy_mode_inactive_highlight_fg = { AnsiColor = "White" },

	quick_select_label_bg = { Color = "#bcc7dc" },
	quick_select_label_fg = { Color = "#263141" },
	quick_select_match_bg = { AnsiColor = "Navy" },
	quick_select_match_fg = { Color = "#e1e2e9" },

	input_selector_label_bg = { AnsiColor = "Black" },
	input_selector_label_fg = { Color = "#e1e2e9" },

	launcher_label_bg = { AnsiColor = "Black" },
	launcher_label_fg = { Color = "#e1e2e9" },

	tab_bar = {
		background = "#111318",

		active_tab = {
			bg_color = "#282a2f",
			fg_color = "#e1e2e9",
			intensity = "Normal",
			underline = "None",
			italic = false,
			strikethrough = false,
		},

		inactive_tab = {
			bg_color = "#1d2024",
			fg_color = "#c3c6cf",
		},

		inactive_tab_hover = {
			bg_color = "#32353a",
			fg_color = "#e1e2e9",
			italic = true,
		},

		new_tab = {
			bg_color = "#1d2024",
			fg_color = "#c3c6cf",
		},

		new_tab_hover = {
			bg_color = "#32353a",
			fg_color = "#e1e2e9",
			italic = true,
		},

		inactive_tab_edge = "#8d9199",
	},
}

local window_frame = {
	active_titlebar_bg = "#111318",
	inactive_titlebar_bg = "#111318",
}

return { color_scheme = color_scheme, window_frame = window_frame }
